#!/usr/bin/env bash
# setup-invidious.sh
# ---------------------------------------------------------------------------
# Clones the official Invidious repo (for Postgres init SQL + scripts), then
# starts Invidious using the official *pre-built* Quay images — no local
# `docker build`, so Docker BuildKit is not required.
#
# Afterward set in OwnTube .env:
#   PIPED_BASE_URL=disabled
#   INVIDIOUS_BASE_URL=http://localhost:3001
#
# Usage:  bash scripts/setup-invidious.sh
# ---------------------------------------------------------------------------
set -euo pipefail

# Prefer BuildKit when any image build happens (not required for this path).
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OWNTUBE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
INVIDIOUS_DIR="$(cd "$OWNTUBE_DIR/.." && pwd)/invidious"
COMPOSE_FILE="$INVIDIOUS_DIR/docker-compose.owntube-local.yml"

# Detect docker compose command (V2 plugin vs V1 standalone binary)
if docker compose version &>/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose &>/dev/null; then
  DC=(docker-compose)
else
  echo "ERROR: Neither 'docker compose' (V2) nor 'docker-compose' (V1) found."
  echo "  Install Docker Engine + compose plugin (e.g. pacman -S docker docker-compose)"
  exit 1
fi
echo "==> Using compose command: ${DC[*]}"

echo "==> Cloning Invidious into $INVIDIOUS_DIR"
if [ -d "$INVIDIOUS_DIR/.git" ]; then
  echo "    Already cloned — pulling latest…"
  git -C "$INVIDIOUS_DIR" pull --ff-only
else
  git clone --depth 1 https://github.com/iv-org/invidious.git "$INVIDIOUS_DIR"
fi

if [ ! -d "$INVIDIOUS_DIR/config/sql" ] || [ ! -f "$INVIDIOUS_DIR/docker/init-invidious-db.sh" ]; then
  echo "ERROR: Invidious repo missing config/sql or docker/init-invidious-db.sh"
  exit 1
fi

# hmac_key: long random secret (Invidious docs suggest pwgen-style uniqueness).
HMAC_KEY=$(openssl rand -hex 16)
# invidious_companion_key MUST be exactly 16 characters (Invidious config validation).
# openssl rand -hex 8 → 16 hex chars. Must match companion SERVER_SECRET_KEY.
COMPANION_KEY=$(openssl rand -hex 8)

INV_IMAGE="quay.io/invidious/invidious:latest"
case "$(uname -m)" in
aarch64 | arm64) INV_IMAGE="quay.io/invidious/invidious:latest-arm64" ;;
esac

echo "==> Writing $COMPOSE_FILE (pre-built images, port 3001)"
# Paths must be absolute so compose works regardless of cwd / project name.
cat >"$COMPOSE_FILE" <<EOF
# Generated by OwnTube scripts/setup-invidious.sh — do not edit by hand.
# https://docs.invidious.io/installation/ (Docker-compose production)

services:
  invidious:
    image: ${INV_IMAGE}
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: invidious-db
          port: 5432
        check_tables: true
        external_port: 3001
        domain: localhost
        https_only: false
        statistics_enabled: false
        hmac_key: "${HMAC_KEY}"
        invidious_companion:
          - private_url: "http://companion:8282/companion"
        invidious_companion_key: "${COMPANION_KEY}"
    depends_on:
      invidious-db:
        condition: service_healthy
      # Invidious 2.x + companion: video API may return empty/bad data if companion is not ready yet.
      companion:
        condition: service_healthy
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/stats || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  companion:
    image: quay.io/invidious/invidious-companion:latest
    restart: unless-stopped
    environment:
      - SERVER_SECRET_KEY=${COMPANION_KEY}
    cap_drop:
      - ALL
    read_only: true
    volumes:
      - companioncache:/var/tmp/youtubei.js:rw
    security_opt:
      - no-new-privileges:true
    depends_on:
      invidious-db:
        condition: service_healthy

  invidious-db:
    image: docker.io/library/postgres:14
    restart: unless-stopped
    volumes:
      - invidious-postgresdata:/var/lib/postgresql/data
      - ${INVIDIOUS_DIR}/config/sql:/config/sql
      - ${INVIDIOUS_DIR}/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kemal -d invidious"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  invidious-postgresdata:
  companioncache:
EOF

echo "==> Starting Invidious (pull + up)…"
(
  cd "$INVIDIOUS_DIR"
  "${DC[@]}" -f "$(basename "$COMPOSE_FILE")" up -d
)

echo ""
echo "Invidious is starting on http://127.0.0.1:3001"
echo "  First boot can take 1–3 minutes (Postgres init + migrations)."
echo "  Logs:  cd $INVIDIOUS_DIR && ${DC[*]} -f $(basename "$COMPOSE_FILE") logs -f invidious"
echo ""
echo "  IMPORTANT: Invidious uses host port 3001. Run OwnTube on port 3000 only:"
echo "    pnpm dev"
echo "  Do NOT use  pnpm dev -- -p 3001  while Invidious is on 3001 — OwnTube would"
echo "  fetch itself instead of Invidious (search/watch HTTP 404)."
echo ""
echo "  OwnTube .env:"
echo "    PIPED_BASE_URL=disabled"
echo "    INVIDIOUS_BASE_URL=http://127.0.0.1:3001"
echo ""
echo "  Then from the OwnTube repo:  pnpm dev"
